# -*- coding: utf-8 -*-
"""Currency Risk Summary Table

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVT9vUIdt_jVKsgFk9NZH3TrH9DRT3KD
"""

import pandas as pd
from google.colab import drive
from tabulate import tabulate
import os

drive.mount('/content/drive')

!python 'drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-CAD Interest Rate Parity Forecasts'
!python 'drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-CHF Interest Rate Parity Forecasts'
!python 'drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-CHF Interest Rate Parity Forecasts'
!python
!python

#exec(open('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-CAD Interest Rate Parity Forecasts').read())
#exec(open('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-CHF Interest Rate Parity Forecasts').read())
#exec(open('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-CHF Interest Rate Parity Forecasts').read())
#exec(open('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-GBP Interest Rate Parity Forecasts').read())
#exec(open('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data Analysis Scripts/USD-EUR Interest Rate Parity Forecasts').read())

timestamp = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Timestamp.csv')
print(timestamp)

cad_data = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-CAD Exposure Forecasts.csv', index_col = False)
chf_data = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-CHF Exposure Forecasts.csv', index_col = False)
jpy_data = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY Exposure Forecasts.csv', index_col = False)
gbp_data = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-GBP Exposure Forecasts.csv', index_col = False)
eur_data = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-EUR Exposure Forecasts.csv', index_col = False)

cad_r = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-CAD R-Squared.csv', index_col = False)
chf_r = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-CHF R-Squared.csv', index_col = False)
jpy_r = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY R-Squared.csv', index_col = False)
gbp_r = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-GBP R-Squared.csv', index_col = False)
eur_r = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-EUR R-Squared.csv', index_col = False)

cad_error = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-CAD Error.csv', index_col = False)
chf_error = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-CHF Error.csv', index_col = False)
jpy_error = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY Error.csv', index_col = False)
gbp_error = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-GBP Error.csv', index_col = False)
eur_error = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-EUR Error.csv', index_col = False)

forecasts_labels = cad_data.iloc[:,0]

cad_forecasts = cad_data.iloc[:,1]
chf_forecasts = chf_data.iloc[:,1]
jpy_forecasts = jpy_data.iloc[:,1]
gbp_forecasts = gbp_data.iloc[:,1]
eur_forecasts = eur_data.iloc[:,1]

forecasts_dataframe = pd.DataFrame(forecasts_labels)
forecasts_dataframe['USD/CAD'] = cad_forecasts
forecasts_dataframe['USD/CHF'] = chf_forecasts
forecasts_dataframe['USD/JPY'] = jpy_forecasts
forecasts_dataframe['USD/GBP'] = gbp_forecasts
forecasts_dataframe['USD/EUR'] = eur_forecasts
print(forecasts_dataframe)

error_tables_labels = cad_r.iloc[:,0]

cad_r_col = cad_r.iloc[:,1]
chf_r_col = chf_r.iloc[:,1]
jpy_r_col = jpy_r.iloc[:,1]
gbp_r_col = gbp_r.iloc[:,1]
eur_r_col = eur_r.iloc[:,1]

r_dataframe = pd.DataFrame(error_tables_labels)
r_dataframe['USD/CAD'] = cad_r_col
r_dataframe['USD/CHF'] = chf_r_col
r_dataframe['USD/JPY'] = jpy_r_col
r_dataframe['USD/GBP'] = gbp_r_col
r_dataframe['USD/EUR'] = eur_r_col
print(r_dataframe)

cad_error_col = cad_error.iloc[:,1]
chf_error_col = chf_error.iloc[:,1]
jpy_error_col = jpy_error.iloc[:,1]
gbp_error_col = gbp_error.iloc[:,1]
eur_error_col = eur_error.iloc[:,1]

error_dataframe = pd.DataFrame(error_tables_labels)
error_dataframe['USD/CAD'] = cad_error_col
error_dataframe['USD/CHF'] = chf_error_col
error_dataframe['USD/JPY'] = jpy_error_col
error_dataframe['USD/GBP'] = gbp_error_col
error_dataframe['USD/EUR'] = eur_error_col
print(error_dataframe)