# -*- coding: utf-8 -*-
"""USD-JPY Interest Rate Parity Forecasts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ro79C5auRJsbVNm3bMnc_CkucFRMrYEX

## USD-EUR
"""

pip install fredapi

pip install nasdaq-data-link

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error
from tabulate import tabulate
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from fredapi import Fred
import datetime
import requests
import io
import os
from sklearn.preprocessing import PolynomialFeatures
import nasdaqdatalink

from google.colab import drive
drive.mount('/content/drive')

model_data = pd.read_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/USD-JPY Model IP Data.csv')

df = pd.DataFrame(model_data)

date = df['Date']
usd_rate = df['USD Rate']
jpy_rate = df['JPY Rate']
current_spot = df['Spot Rate']
M2 = df['US M2']
lag_spot = df['Last Month Spot Rate']

x_multi_var = np.array(list(zip(usd_rate, jpy_rate, M2, lag_spot)))
y_fx = current_spot

x_train, x_test, y_train, y_test = train_test_split(x_multi_var, y_fx, train_size=0.8, test_size=0.2, random_state=1)
model_multi = LinearRegression()
model_multi.fit(x_train, y_train)
print(model_multi.score(x_train, y_train))
print(model_multi.score(x_test, y_test))

model_multi = LinearRegression()
model_multi.fit(x_multi_var, y_fx)
y_fx_multi_predict = model_multi.predict(x_multi_var)
y_fx_multi_mse = mean_squared_error(y_fx, y_fx_multi_predict)
print(model_multi.score(x_multi_var, y_fx))
print(y_fx_multi_mse)

date = date.astype(str)
plt.figure(figsize=(12,6))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_multi_predict)
plt.title("Linear Multivariable Regression: USD/JPY Exchange Rate")
plt.legend(['4var Poly'])
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=1)
plt.show()

poly = PolynomialFeatures(degree=5)
x_poly = poly.fit_transform(x_multi_var)
model_poly = LinearRegression()
model_poly.fit(x_poly, y_fx)
y_fx_poly_predict = model_poly.predict(x_poly)
y_fx_poly_mse = mean_squared_error(y_fx, y_fx_poly_predict)
print(model_poly.score(x_poly, y_fx))
print(y_fx_poly_mse)

plt.figure(figsize=(14,6))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_poly_predict, color='black')
plt.legend(['4var Poly'])
plt.title("Polynomial Regression: USD/JPY Exchange Rate")
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=5)
plt.show()

r_squared_list = []
mse_list = []
a = range(1,10,1)
for i in a:
    poly = PolynomialFeatures(degree=i)
    x_poly = poly.fit_transform(x_multi_var)

    model_poly = LinearRegression()
    model_poly.fit(x_poly, y_fx)
    y_pred = model_poly.predict(x_poly)

    r_squared = model_poly.score(x_poly, y_fx)
    mse = mean_squared_error(y_pred, y_fx)

    r_squared_list.append(r_squared)
    mse_list.append(mse)

# Shows that the degree of 4 has the best fit for the polynomial regression
plt.figure(figsize=(15,5))
ax1 = plt.subplot(1,2,1)
plt.plot(a, r_squared_list)
plt.xlabel("Polynomial Degree")
plt.ylabel("R_Squared")
ax2 = plt.subplot(1,2,2)
plt.plot(a, mse_list)
plt.xlabel("Polynomial Degree")
plt.ylabel("MSE")

plt.subplots_adjust(0.0005)

plt.show()

ridge = Ridge(alpha=0.001)
ridge.fit(x_multi_var, y_fx)
y_fx_ridge_predict = ridge.predict(x_multi_var)
y_fx_ridge_mse = mean_squared_error(y_fx, y_fx_ridge_predict)
print(ridge.score(x_multi_var, y_fx))
print(y_fx_ridge_mse)

plt.figure(figsize=(14,5))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_ridge_predict, color='r')
plt.legend(['4var Ridge'])
plt.title("Ridge Regression: USD/JPY Exchange Rate")
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=5)
plt.show()

lasso = Lasso(alpha=0.001)
lasso.fit(x_multi_var, y_fx)
y_fx_lasso_predict = lasso.predict(x_multi_var)
y_fx_lasso_mse = mean_squared_error(y_fx, y_fx_lasso_predict)
print(lasso.score(x_multi_var, y_fx))
print(y_fx_lasso_mse)

plt.figure(figsize=(14,5))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_lasso_predict, color='g')
plt.legend(['4var Lasso'])
plt.title("Lasso Regression: USD/JPY Exchange Rate")
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=5)
plt.show()

plt.figure(figsize=(14,5))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_multi_predict, color='b')
plt.plot(date, y_fx_poly_predict, color='black')
plt.plot(date, y_fx_ridge_predict, color='r')
plt.plot(date, y_fx_lasso_predict, color='g')
plt.legend(['4var Multi','4var Poly','4var Ridge','4var Lasso'])
plt.title("Various Regressions: USD/JPY Exchange Rate")
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=5)
plt.show()

decision_tree = DecisionTreeRegressor(random_state = 0)
decision_tree.fit(x_train, y_train)
y_fx_decision_tree_predict = decision_tree.predict(x_multi_var)
y_fx_decision_tree_mse = mean_squared_error(y_fx, y_fx_decision_tree_predict)
print(decision_tree.score(x_multi_var, y_fx))
print(y_fx_decision_tree_mse)

plt.figure(figsize=(14,5))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_decision_tree_predict, color='purple')
plt.legend(['4var Decision Tree'])
plt.title("Decision Tree: USD/JPY Exchange Rate")
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=5)
plt.show()

support_vector = SVR()
support_vector.fit(x_train, y_train)
y_fx_support_vector_predict = support_vector.predict(x_multi_var)
y_fx_support_vector_mse = mean_squared_error(y_fx, y_fx_support_vector_predict)
print(support_vector.score(x_multi_var, y_fx))
print(y_fx_support_vector_mse)

plt.figure(figsize=(14,5))
plt.scatter(date, y_fx, alpha=0.4)
plt.plot(date, y_fx_support_vector_predict, color='orange')
plt.legend(['4var Support Vector Regression'])
plt.title("Support Vector Regression: USD/JPY Exchange Rate")
plt.xlabel("Date")
plt.ylabel("Exchange Rate")
plt.xticks(fontsize=5)
plt.show()

prediction_table_data = {"Date": date, "Actual FX Rate": y_fx,  "Multivariable Regression Prediction": pd.Series(y_fx_multi_predict), "Ridge Regression Prediction": pd.Series(y_fx_ridge_predict),
                         "Lasso Regression Prediction": pd.Series(y_fx_lasso_predict), "Decision Tree Prediction": pd.Series(y_fx_decision_tree_predict)}
prediction_table_col_names = ["Date", "Actual FX Rate", "Multivariable Regression Prediction", "Ridge Regression Prediction", "Lasso Regression Prediction", "Decision Tree Prediction"]
prediction_dataframe = pd.DataFrame(prediction_table_data)
print(tabulate(prediction_dataframe, headers = prediction_table_col_names))

# Nasdaq API Key: BHonhZCZeZLdxpEHrZex
fred = Fred(api_key = '7e15a33cca1e5930755600689819ea4a')
current_time = datetime.date.today()
today = str(current_time.year) + "-" + str(current_time.month) + "-" + str(current_time.day)
one_month = current_time.replace(day = 1)
one_month_ago = one_month - datetime.timedelta(days = 1)
one_month_ago_first = one_month_ago.replace(day = 1)
one_month_ago_first_str = one_month_ago_first.strftime('%m/%d/%Y')
one_month_ago_first_datetime = datetime.datetime.strptime(one_month_ago_first_str, '%m/%d/%Y')
last_month = str(one_month_ago.year) + "-" + str(one_month_ago.month) + "-" + str(one_month_ago.day)
two_months_ago = one_month_ago_first - datetime.timedelta(days = 1)
two_months_ago_first = two_months_ago.replace(day = 1)
three_months_ago = two_months_ago_first - datetime.timedelta(days = 1)
three_months_ago_first = three_months_ago.replace(day = 1)
current_month_first = current_time.replace(day = 1)
one_months = str(one_month_ago.year) + "-" + str(one_month_ago.month) + "-" + str(one_month_ago.day)
two_months = str(two_months_ago.year) + "-" + str(two_months_ago.month) + "-" + str(two_months_ago.day)
three_months = str(three_months_ago.year) + "-" + str(three_months_ago.month) + "-" + str(three_months_ago.day)
two_months_ago_first_str = two_months_ago_first.strftime('%m/%d/%Y')
temp = datetime.datetime.strptime(one_month_ago_first_str, '%m/%d/%Y')

current_date_series = pd.Series(current_month_first)
one_date_series = pd.Series(one_month_ago_first)

new_date = one_date_series.append(current_date_series, ignore_index = True)
new_usd_rate = fred.get_series('GS10', observation_start = three_months, observation_end = one_month)
new_jpy_rate = fred.get_series('IRLTLT01JPM156N', observation_start = three_months, observation_end = one_month)
new_current_spot = 1 / fred.get_series('EXJPUS', observation_start = one_month_ago_first, observation_end = current_month_first)
new_M2 = fred.get_series('M2NS', observation_start = three_months, observation_end = one_months)
new_lag_spot = 1 / fred.get_series('EXJPUS', observation_start = two_months, observation_end = today)
print(new_jpy_rate)

new_x_multi_var = np.array(list(zip(new_usd_rate, new_jpy_rate, new_M2, new_lag_spot)))
new_y_fx = new_current_spot

new_y_fx_multi_predict = model_multi.predict(new_x_multi_var)
new_y_fx_ridge_predict = ridge.predict(new_x_multi_var)
new_y_fx_lasso_predict = lasso.predict(new_x_multi_var)
new_y_fx_decision_tree_predict = decision_tree.predict(new_x_multi_var)

new_prediction_table_data = {"Date": new_date, "Multivariable Regression Prediction": pd.Series(new_y_fx_multi_predict), "Ridge Regression Prediction": pd.Series(new_y_fx_ridge_predict),
                         "Lasso Regression Prediction": pd.Series(new_y_fx_lasso_predict), "Decision Tree Prediction": pd.Series(new_y_fx_decision_tree_predict)}
new_prediction_table_col_names = ["Date", "Actual FX Rate", "Multivariable Regression Prediction", "Ridge Regression Prediction", "Lasso Regression Prediction", "Decision Tree Prediction"]
new_column_data = [new_current_spot[0], "Not Available"]
new_prediction_dataframe = pd.DataFrame(new_prediction_table_data)
new_prediction_dataframe.insert(1, 'Actual FX Rate', new_column_data)
new_actual_data = {"Spot Rate": new_current_spot}
new_actual_data_col_names = ["Spot Rate"]
new_actual_dataframe = pd.DataFrame(new_actual_data)
print(new_column_data)
print(tabulate(new_actual_dataframe, headers = new_actual_data_col_names))
print(tabulate((new_prediction_dataframe), headers = new_prediction_table_col_names))

dataframe_test_date_str = prediction_dataframe.iloc[-1, 0]
dataframe_test_date = datetime.datetime.strptime(dataframe_test_date_str, '%m/%d/%Y')
last_spot = df.iloc[-1, 3]
print(df)
print(dataframe_test_date)

condition_1 = (one_month_ago_first_datetime == dataframe_test_date)
condition_2 = (new_current_spot[0] != last_spot)

if condition_1 == True and condition_2 == True:
  new_date_addition = one_month_ago_first.strftime('%m/%d/%Y')
  row_addition_dict = {'Date': [new_date_addition], 'USD Rate':[new_usd_rate[0]], 'JPY Rate': [new_jpy_rate[0]], 'Spot Rate': [new_current_spot[0]], 'US M2': [new_M2[0]], 'Last Month Spot Rate': [new_lag_spot[0]]}
  additions_df = pd.DataFrame(row_addition_dict)
  df = df.append(additions_df, ignore_index = True)
  last_spot = df.iloc[-1, 3]
  condition_1 = (one_month_ago_first == dataframe_test_date)
  condition_2 = (new_current_spot[0] != last_spot)
  print(df)
  os.remove('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/USD-JPY Model IP Data.csv')
  df.to_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/USD-JPY Model IP Data.csv', index = False)
else:
  print(df)

output_data = {
    "Machine Learning Model": ["Multivariable Linear Regression", "Ridge Regression", "Lasso Regression", "Decision Tree Regression"],
    "Predicted Rate": [new_y_fx_multi_predict[1], new_y_fx_ridge_predict[1], new_y_fx_lasso_predict[1], new_y_fx_decision_tree_predict[1]]
}
measurement_dataframe = pd.DataFrame(output_data)
prediction_mean = measurement_dataframe['Predicted Rate'].mean()
prediction_median = measurement_dataframe['Predicted Rate'].median()
prediction_std = measurement_dataframe['Predicted Rate'].std()
mean_per_dollar_exposure = prediction_mean - new_current_spot[0]
median_per_dollar_exposure = prediction_median - new_current_spot[0]
per_million_mean_exposure = mean_per_dollar_exposure * 1000000
per_million_median_exposure = median_per_dollar_exposure * 1000000

export_data = {
    "Machine Learning Model": ["Multivariable Linear Regression", "Ridge Regression", "Lasso Regression", "Decision Tree Regression", "Mean", "Median", "Standard Deviation", "Previous Spot Rate", "Mean Per-Dollar Exposure",
                               "Median Per-Dollar Exposure", "Mean Per-Million Exposure", "Median Per-Million Exposure"],
    "Predicted Rate": [new_y_fx_multi_predict[1], new_y_fx_ridge_predict[1], new_y_fx_lasso_predict[1], new_y_fx_decision_tree_predict[1], prediction_mean, prediction_median, prediction_std, new_current_spot[0],
                       mean_per_dollar_exposure, median_per_dollar_exposure, per_million_mean_exposure, per_million_median_exposure]
}
export_dataframe = pd.DataFrame(export_data)
os.remove('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY Exposure Forecasts.csv')
export_dataframe.to_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY Exposure Forecasts.csv', index = False)

r_table = {
    "Machine Learning Model": ["Multivariable Linear Regression", "Ridge Regression", "Lasso Regression", "Decision Tree Regression"],
    "R-Squared": [model_multi.score(x_multi_var, y_fx), ridge.score(x_multi_var, y_fx), lasso.score(x_multi_var, y_fx), decision_tree.score(x_multi_var, y_fx)]
}
error_table = {
    "Machine Learning Model": ["Multivariable Linear Regression", "Ridge Regression", "Lasso Regression", "Decision Tree Regression"],
    "Mean_Squared Error": [y_fx_multi_mse, y_fx_ridge_mse, y_fx_lasso_mse, y_fx_decision_tree_mse]
}
r_dataframe = pd.DataFrame(r_table)
error_dataframe = pd.DataFrame(error_table)
os.remove('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY R-Squared.csv')
r_dataframe.to_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY R-Squared.csv', index = False)
os.remove('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY Error.csv')
error_dataframe.to_csv('drive/MyDrive/FX Risk Management Model/Interest Rate Parity Model/Data/Interest Rate Parity USD-JPY Error.csv', index = False)